Sage-Bionetworks/rocc-app

README.md
package.json
proxy.conf.json
src/app/component/challenges/challenges.component.ts
src/environments/environment.prod.ts
src/environments/environment.ts

List challenges using ChallengeService (Part 2/2)

---

.gitmodules
angular.json
package-lock.json
package.json
src/app/app.component.html
src/app/app.module.ts
src/app/component/home/home.component.ts

Fixes #20 
Preview:
The string "sage-angular works!" above is actually the example component `SageAngularComponent` imported from the library [@sage-bionetworks/sage-angular](https://github.com/Sage-Bionetworks/sage-angular).

Add library @sage-bionetworks/sage-angular as git submodule

---

.gitignore
package-lock.json
package.json

Add the script `npm run update:dependencies` and its shortcut `npm run update:deps` to update the dependencies of the project.

Add npm run update:deps

---

.github/workflows/ci.yml

Publish app to GH Pages

---

package-lock.json
package.json
src/app/components/database-seed/database-seed.component.ts
src/app/read-json.ts
src/app/seeds/dream/tags.json
tsconfig.json

Based on PR #48, seed all tags from `tags.json` to database. 
Two parts could be improved:
- I tried `JSON.parse` function to read `tags.json` directly, but somehow it did not work out. So I changed compiler in `tsconfig.json` and import json module to load the `tags.json`.
- Tags now are added one by one in a "for" loop and the loop cannot be directly followed by `toPromise()`. Since adding challenges data will be dependent on this step, need to find a way to connect these two steps sequentially.

Seed all tags to database

---

src/app/components/database-seed/database-seed.component.ts
src/app/seeds/dream/organizations.json

One of steps for #42:
Seeding organization to database:

Seed organizations to database

---

src/app/components/database-seed/database-seed.component.ts
src/app/seeds/dream/tags.json

Seed tags using schemas 1.6.0

---

angular.json

Increase budget max size to 2mb

---

src/app/components/database-seed/database-seed.component.ts
src/environments/environment.ts

Set challenge seeding concurrency to 1

---

package-lock.json
src/app/components/database-seed/database-seed.component.ts
src/app/seeds/dream/challenge-platforms.json
src/app/seeds/dream/challenges.json

Seed challenge platforms

---

src/app/pages/organizations/organization-list/organization-list.component.html
src/app/pages/organizations/organization-list/organization-list.component.spec.ts
src/app/pages/organizations/organization-list/organization-list.component.ts
src/app/pages/organizations/organization-new/organization-new.component.html
src/app/pages/organizations/organization-new/organization-new.component.spec.ts
src/app/pages/organizations/organization-new/organization-new.component.ts
src/app/pages/organizations/organization-view/organization-view.component.html
src/app/pages/organizations/organization-view/organization-view.component.spec.ts
src/app/pages/organizations/organization-view/organization-view.component.ts
src/app/pages/organizations/organizations-routing.module.ts
src/app/pages/organizations/organizations.component.html
src/app/pages/organizations/organizations.module.ts
src/app/shallowEqual.ts

Add organization pages and routing

Add organization pages

---

.github/CONTRIBUTING.md
.github/workflows/ci.yml
.github/workflows/lock.yml
docker-compose.yml

Update CI/CD workflow to build and push Docker image

---

.env.example
README.md
src/config/config.json

The project is virtually at version 0.3.0. Just updating the app version is a few remaining files.

Bump project version to 0.3.0

---

src/app/pages/challenges/challenge-list-item/challenge-list-item.component.html
src/app/pages/challenges/challenge-list-item/challenge-list-item.component.ts
src/app/pages/challenges/challenge-list/challenge-list.component.html
src/app/pages/challenges/challenge-view/challenge-view.component.html
src/app/pages/challenges/challenge-view/challenge-view.component.ts

Route to challenge details page and load challenge data

---

src/app/seeds/development/challenges.json

Related to https://github.com/Sage-Bionetworks/rocc-schemas/issues/158

Add Challenge.doi

---

src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.html
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.ts
src/app/pages/challenge/challenge-new/challenge-new.component.ts
src/app/seeds/development/org-memberships.json
src/app/shared/database-seed/database-seed.component.ts

Related to https://github.com/Sage-Bionetworks/rocc-schemas/pull/160

Add org membership

---

src/app/shared/database-seed/database-seed.component.ts

Fix non existing Challenge.platformId in seeds

---

src/app/pages/account/account.module.ts
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.html
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.scss
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.ts
src/app/shared/material/material.module.ts
src/config/config.json

Implement user profile bar

---

src/app/pages/signup/signup.component.ts

Redirect to user page upon successful user creation

---

src/app/pages/organization/org-new/org-new.component.ts

Redirect to Org page upon successfull creation

---

src/app/pages/challenge/challenge-new/challenge-new.component.ts

Redirect to challenge page upon creation

---

.github/CONTRIBUTING.md
README.md
docker-compose.yml
src/config/config.json

Bump project version to 0.4.0

---

src/app/pages/account/org-account/org-account.component.scss
src/app/pages/account/user-account/user-account.component.scss
src/app/pages/challenge/challenge.component.scss
src/app/pages/organization/organization.component.scss

Disable mat-ink-bar animation

---

src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/pages/signin/signin.component.html
src/app/pages/signin/signin.component.scss
src/app/pages/signin/signin.component.ts
src/app/pages/signin/signin.module.ts
src/app/pages/signup/signup.component.ts
src/app/shared/auth/auth.module.ts
src/app/shared/auth/auth.service.spec.ts
src/app/shared/auth/auth.service.ts
src/app/shared/auth/token.service.spec.ts
src/app/shared/auth/token.service.ts
src/app/shared/auth/user.service.spec.ts
src/app/shared/auth/user.service.ts

Authenticate user

---

src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.ts

Fix the avatar of users created using the sign up form

---

src/app/pages/challenge/challenge-new/challenge-new.component.html
src/app/pages/challenge/challenge-new/challenge-new.component.scss
src/app/pages/challenge/challenge-new/challenge-new.component.ts
src/app/pages/challenge/challenge-new/challenge-new.module.ts
src/app/pages/homepage/homepage.component.html
src/app/seeds/development/organizations.json
src/config/config.json

Fixes #195 
- In the Challenge registration page, replace the input field by a select menu that lists the organizations a User belong to.
- An improvement would be to include the org avatar in the select menu.

Add menu that list authenticated userr orgs

---

src/app/pages/account/account.module.ts
src/app/pages/account/user-account/tab.model.ts
src/app/pages/account/user-account/user-account-tabs.ts
src/app/pages/account/user-account/user-account.component.html
src/app/pages/account/user-account/user-account.component.scss
src/app/pages/account/user-account/user-account.component.ts
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.html
src/app/pages/account/user-account/user-profile-starred/user-profile-starred.component.html
src/app/pages/account/user-account/user-profile-starred/user-profile-starred.component.spec.ts
src/app/pages/account/user-account/user-profile-starred/user-profile-starred.component.ts

Fixes #237 
- Improve tabs of user profile page.
- List starred challenges on user profile page.
- Appearance of starred challenges will be improved later.

Show the challenges starred by a user

---

src/app/app-routing.module.ts

Protect new challenge and other pages with AuthGuard

---

src/app/pages/account/user-account/user-profile-overview/user-profile-overview.component.html

Show user bio

---

src/app/pages/challenge/challenge-overview/challenge-overview.component.html
src/app/seeds/development/challenges.json

Related to https://github.com/Sage-Bionetworks/rocc-schemas/pull/182

Add Challenge.topics

---

src/app/pages/homepage/homepage.component.html

Fixes #226 
- https://github.com/Sage-Bionetworks/rocc-service/issues/181

Hide that users canhost challenges

---

src/app/app.component.ts

Connect Profile button in user menu to user profile page

---

src/app/pages/challenge/challenge-data.service.ts
src/app/pages/challenge/challenge-routing.module.ts
src/app/pages/challenge/challenge-stargazers/challenge-stargazers.component.html
src/app/pages/challenge/challenge-stargazers/challenge-stargazers.component.scss
src/app/pages/challenge/challenge-stargazers/challenge-stargazers.component.spec.ts
src/app/pages/challenge/challenge-stargazers/challenge-stargazers.component.ts
src/app/pages/challenge/challenge.component.ts
src/app/pages/challenge/challenge.module.ts
src/app/pages/homepage/homepage.component.html

- Fixes #258 
- Depends on https://github.com/Sage-Bionetworks/rocc-service/issues/182

Add challenge stargazers page

---

src/app/seeds/development/challenges.json
src/app/shared/cards/challenge-card/challenge-card.component.html

- add [BraTs challenge](https://www.synapse.org/#!Synapse:syn25829067)
- replace `name` with `displayName` on challenge card
note: to avoid multiple platforms, I only make it associated with synapse for now.

Add braTs challenge data

---

README.md
docker-compose.yml
src/app/shared/database-seed/database-seed.component.ts
src/config/config.json

- Restore seed concurrency to 10 (100 failed on test server with nginx)

Prepare release 0.5.2

---

src/app/shared/cards/challenge-card/challenge-card.component.html
src/app/shared/cards/challenge-card/challenge-card.component.scss
src/app/shared/cards/challenge-card/challenge-card.component.ts

- fixes #297 
- make platform redirect to platform website

Show finger cursor on challenge card elements that can be clicked

---

src/app/pages/signin/signin.component.html
src/app/pages/signup/signup.component.ts

Fix redirection to login page after successfully creating an account

---

src/app/pages/search/challenge-search/challenge-search.component.html
src/app/pages/search/challenge-search/challenge-search.component.scss
src/app/pages/search/challenge-search/challenge-search.component.ts
src/app/shared/material/material.module.ts

Search Page > Add pagination

---

src/app/pages/account/account.module.ts
src/app/pages/account/user-account/user-account.component.html
src/app/pages/account/user-account/user-account.component.scss
src/app/pages/account/user-account/user-account.component.ts
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.html
src/app/pages/account/user-account/user-profile-bar/user-profile-bar.component.scss
src/app/pages/account/user-account/user-profile-starred/user-profile-starred.component.html
src/app/pages/account/user-account/user-profile-starred/user-profile-starred.component.scss
src/app/pages/account/user-account/user-profile-starred/user-profile-starred.component.ts
src/app/pages/search/challenge-search/challenge-search.component.ts
src/app/pages/signin/signin.component.ts
src/app/shared/cards/challenge-card/challenge-card.component.scss

User Profile > Enable to star/unstar challenges from the starred page

---

src/app/pages/homepage/homepage.component.html
src/app/pages/homepage/homepage.component.ts

Add challenge, user and org counts to home page

---

src/app/pages/challenge/challenge-overview/challenge-overview.component.html
src/app/pages/challenge/challenge-overview/challenge-overview.component.scss
src/app/pages/challenge/challenge-overview/challenge-overview.component.ts

- fixes https://github.com/Sage-Bionetworks/rocc/issues/26
- use grid card display with temp avatar,  name and roles of sponsors
- remove unused codes for styles 
Preview
---

Display sponsors on challenge page

---

src/app/pages/search/challenge-search/challenge-search-query.ts
src/app/pages/search/challenge-search/challenge-search.component.ts

Update rocc-client-angular, depending on 
- https://github.com/Sage-Bionetworks/rocc-client-angular/pull/96

Update rocc-client-angular library

---

src/app/pages/homepage/homepage.component.scss

Quick fix for something that's been bothering me...

fix card height

---

src/app/app-routing.module.ts
src/app/app-sections.ts
src/app/pages/about/about.component.html
src/app/pages/about/about.component.scss
src/app/pages/about/about.component.spec.ts
src/app/pages/about/about.component.ts
src/app/pages/about/about.module.ts
src/app/pages/about/index.ts

A new page/component dedicated to hold information about the ROCC app, motivation, and background.
For now, the page will compose of information from the two-pager that @jiaxinmachine88 wrote up last year.  Wording and images can be edited/added at a later time.

Add 'About' section to the app

---

.vscode/extensions.json
docs/style-guide.md

Describe style guide workflow
